' Gambas module file

Public Sub main()
  
  Dim idtmp As String 'variable que nos sirve para guardar los id del elemento, antes que se genere otro.
  
  Dim b As New Bingo
  
  Dim tempEleSonido As ElementoSonido ''test de pruebas
  Dim tempEleImagen As ElementoImagen ''test de pruebas
  
  Dim tempEleNegro As ElementoNegro '' exclusivo para los cartones
  Dim tempEleBlanco As ElementoBlanco '' excluisvo para los cartones
  Dim tempEletexto As ElementoTexto
  
  Dim tempCarton As Carton
  
  '  Print "empiezo..."
  
  '*****************************************************************************************
  '1º, creo el elemnto en el bingo
  
  tempEleSonido = New ElementoSonido 'asi al instanciarse, tambien se va a crear el id
  tempEleSonido.rutasonido = "hola.mp3"
  b.agregarElementoBingo(tempEleSonido) '' se debe de agregar a los elemntos del bingo
  
  idtmp = tempEleSonido.id
  '2º, luego creo el elemento relacionado en el carton...
  tempEletexto = New ElementoTexto
  tempEletexto.texto = "HOLA"
  tempEletexto.enlace = idtmp
  b.agregarElementoCarton(tempEletexto) '' se debe de agregar a los elemntos del bingo
  
  '*****************************************************************************************
  '1º, creo el elemnto en el bingo
  tempEletexto = New ElementoTexto
  tempEletexto.texto = "4x4"
  b.agregarElementoBingo(tempEletexto) '' se debe de agregar a los elemntos del bingo
  
  idtmp = tempEletexto.id
  '2º, luego creo el elemento relacionado en el carton...
  tempEletexto = New ElementoTexto
  tempEletexto.texto = "16"
  tempEletexto.enlace = idtmp
  
  b.agregarElementoCarton(tempEletexto) '' se debe de agregar a los elemntos del bingo
  
  '*****************************************************************************************
  tempEletexto = New ElementoTexto ''vuelvo a instanciar para generar el id distinto al anterior
  tempEletexto.texto = "4x2"
  b.agregarElementoBingo(tempEletexto) '' se debe de agregar a los elemntos del bingo
  
  idtmp = tempEletexto.id
  '2º, luego creo el elemento relacionado en el carton...
  tempEletexto = New ElementoTexto
  tempEletexto.texto = "8"
  tempEletexto.enlace = idtmp
  b.agregarElementoCarton(tempEletexto) '' se debe de agregar a los elemntos del bingo
  
  'voy a agregar varios cartones...
  
  'Creo un carton de varios elementos
  tempCarton = New Carton
  tempCarton.ArraIdElementos.Add(b.ArrayElementosCarton[0].id)
  tempCarton.ArraIdElementos.Add(b.ArrayElementosCarton[1].id)
  tempCarton.ArraIdElementos.Add(b.ArrayElementosCarton[2].id)
  
  b.agregarCarton(tempCarton)
  
  'otro carton con los elementos cambiados de sitio
  
  tempCarton = New Carton
  tempCarton.ArraIdElementos.Add(b.ArrayElementosCarton[1].id)
  tempCarton.ArraIdElementos.Add(b.ArrayElementosCarton[2].id)
  tempCarton.ArraIdElementos.Add(b.ArrayElementosCarton[0].id)
  
  b.agregarCarton(tempCarton)
  
  b.guardarBingo()
  
  Print "termine!!"
  
End
